# Generated by Django 5.1.6 on 2025-02-14 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('severity', models.IntegerField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReliefCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('available_resources', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('disaster', 'Disaster Alert'), ('supply', 'Supply Request'), ('logistics', 'Logistics Update')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity_needed', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('in_progress', 'In Progress')], default='pending', max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRSCM.disaster')),
                ('relief_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRSCM.reliefcenter')),
            ],
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('estimated_arrival', models.DateTimeField()),
                ('status', models.CharField(choices=[('en_route', 'En Route'), ('delivered', 'Delivered'), ('delayed', 'Delayed')], default='en_route', max_length=50)),
                ('supply_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRSCM.supplyrequest')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Relief Center Staff'), ('volunteer', 'Volunteer')], default='volunteer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
