# Generated by Django 5.1.6 on 2025-02-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRSCM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='description',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
