# Generated by Django 5.1.6 on 2025-02-15 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRSCM', '0003_logistics_end_lat_logistics_end_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistics',
            name='supply_request',
        ),
        migrations.AlterField(
            model_name='logistics',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='estimated_arrival',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
